jwt:
  secret: VGhpcyBpcyBhIHNlY3JldCBrZXk=
  lifetime: 20160m

spring:
  mail:
    host: ${email.host}
    port: ${email.port}
    username: ${email.from}
    password: ${email.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: authSecureXPay

  security:
    user:
      password: 181056ad-19df-4265-8169-7e851246fd59

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/securexpay_account
    username: securexpay_account_admin
    password: HeQUUcu\AMIjlJ1N

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

email:
  from: "securexpayhelp@mail.ru"
  password: "kg1WNwuTucR8SMQbfrCp"
  host: "smtp.mail.ru"
  port: 587

server:
  port: 8080