spring:
  security:
    user:
      password: 7757dc59-de4c-47ad-9ec2-d5cf6296e222

  application:
    name: paymentSecureXPay

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

server:
  port: 8081
